# Generated by Django 5.2.2 on 2025-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/covers/'),
        ),
    ]
