# Generated by Django 5.2.2 on 2025-06-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='research/images/')),
                ('published_at', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
